services:
  web:
    build: .
    container_name: jgu-django-prod
    restart: always
    expose:
      - "8080"
    env_file:
      - .env.prod
    volumes:
      - ./static:/static

  proxy:
    image: nginx:latest
    container_name: jgu-nginx-prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/jgu_reviews.conf
      - ./static:/static
    depends_on:
      - web

  my-redis:
    image: redis:latest
    restart: always