# Generated by Django 4.2.18 on 2025-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
