# Generated by Django 4.2.4 on 2024-11-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_remove_review_name_review_reviewer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
